### ISSUE TITLE
Get one or more plugins working

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-lite#5]
Obvious starting point is https://datasette.io/plugins/datasette-cluster-map

Biggest challenge here is the CSS and JavaScript. I could hot-link those out to https://latest-with-plugins.datasette.io/ but that's only a very short term fix.

Ideally the `<script>` and `<link>` tags on the page that link to CSS and JavaScript would work in a way that uses the assets bundled with the plugin.

I may be able to get that to work by extracting them from the HTML, fetching the underlying CSS and JavaScript from the web worker and then injecting the content in as a `data:uri` - though that won't work for CSS files that reference other images with relative URLs inside the CSS.

**Comment by dazzag24** [comment]
+1 for datasette-cluster-map.  I used this plugin a few years ago for a database of airport locations and associated metadata. It makes for a very visually compelling use case.

**Comment by simonw** [comment]
I got some plugins working here:
- https://github.com/simonw/datasette-lite/issues/37#issuecomment-1214427165
