### ISSUE TITLE
Error: Requested 'python-multipart>=0.0.13', but python-multipart==0.0.12 is already installed

### ISSUE THREAD

**Issue by Lewiscowles1986** [simonw/datasette-lite#80]
Hey Simon, Hope you are well

So I noticed this while clearing out my Discord notifications

![Screenshot 2024-11-17 at 12 39 03](https://github.com/user-attachments/assets/8113da28-1122-4aab-b1fc-e8be6ec8e313)

I Don't know Derek, so I kinda thought it was a troll, or inside joke, but then I `curl -t `'d the url and it worked. So I reached out and asked if this happened (it's a wasm app, no server needed was I thought a win).

As I accidentally clicked on the url in terminal, it opened and I saw the bug...

I'm guessing to reproduce, open a private window, and then access the site, as it's local, session, cache storage should be clear and then visit https://lite.datasette.io

> ValueError: Requested 'python-multipart>=0.0.13', but python-multipart==0.0.12 is already installed

Is the error on https://lite.datasette.io/ as it's loading https://lite.datasette.io/

I reported in discord, but maybe it's MIA or will be buried in the chat log, so [link](https://discord.com/channels/823971286308356157/823971286941302908/1307685963824103496)

Interested to read / see a PR on how this gets resolved

**Comment by simonw** [comment]
Confirmed fixed: https://lite.datasette.io/?json=https://gist.github.com/simonw/53ad57ad42c7efe75e2028d975907180
